### ISSUE TITLE
An unexpected panic

### ISSUE THREAD

**Issue by screwyprof** [grosser/go-testcov#14]
I'm trying to run `go-testcov ./...` on one of my projects and I get the following:
```
panic: open products/coolproduct/coolservice/api/backend-server.go: no such file or directory
goroutine 1 [running]:
main.check(...)
	/Users/screwyprof/go/pkg/mod/github.com/grosser/go-testcov@v1.3.0/utils.go:17
main.readFile({0xc0001e251d, 0x10d65a4})
	/Users/screwyprof/go/pkg/mod/github.com/grosser/go-testcov@v1.3.0/utils.go:57 +0x4d
main.configuredUncovered({0xc0001e251d, 0x51})
	/Users/screwyprof/go/pkg/mod/github.com/grosser/go-testcov@v1.3.0/main.go:216 +0x25
main.checkCoverage.func1({0xc0001e2501, 0xc00006e360}, {0xc0002b6000, 0x33, 0x49})
	/Users/screwyprof/go/pkg/mod/github.com/grosser/go-testcov@v1.3.0/main.go:84 +0x87
main.iterateSorted(0xc00006e360, 0xc00010fe88)
	/Users/screwyprof/go/pkg/mod/github.com/grosser/go-testcov@v1.3.0/utils.go:71 +0x1b6
main.checkCoverage({0x10d79d0, 0x2})
	/Users/screwyprof/go/pkg/mod/github.com/grosser/go-testcov@v1.3.0/main.go:81 +0x8c
main.goTestCheckCoverage({0xc000010050, 0x10c00a0, 0x1})
	/Users/screwyprof/go/pkg/mod/github.com/grosser/go-testcov@v1.3.0/main.go:62 +0x25a
main.main()
	/Users/screwyprof/go/pkg/mod/github.com/grosser/go-testcov@v1.3.0/main.go:13 +0x50
```

As it says the path doesn't exit and it shouldn't. I'm running the tool inside  `./coolservice` dir.
I haven't looked though the code, but my wild guess is that `go-testcov` tries to craft the path using the git-remote. Is it really the case? Is there any workaround for this?

**Comment by grosser** [comment]
it tries to read the file that is supposed to be tested
I assume it would work if the test was run from the root directory
```
modulePrefixSize := 3 // foo.com/bar/baz + file.go
```
so it cuts off the first parts and then assumes that rest is a file readable on disk

**Comment by grosser** [comment]
You'd basically need to go into `normalizeModulePath` and see what needs to be changed to support your setup. It might be hard to guess the right path, but maybe we could somehow guess the project root folder and expand from there.

For a quick-fix I can disable the "inline disable" feature when the file cannot be found so you are not completely stuck.

**Comment by grosser** [comment]
ah nvm that won't work either since the total count is also being read from the file :(

**Comment by grosser** [comment]
so only option would be to disable any kind of uncovered support, but that's a core feature ...
lmk if you can reproduce in a public repo and I can debug more

**Comment by screwyprof** [comment]
>> I assume it would work if the test was run from the root directory
Well, I am running it from the root directory.

**Comment by screwyprof** [comment]
It case it help the `go.mod` has the following path:
```
module gitlab.com/CoolCompany/department/products/coolproduct/coolservice
```

In other words the physical path is not the same as the repo path.

The physical path is:
```
 ~/GolandProjects/CoolCompany/coolservice
```

I guess this could be the problem :)

**Comment by screwyprof** [comment]
Unfortunately I don't have time to dive in deeper at the moment. Not that I needed the tool much, just like to try new things  out :)

**Comment by eatwithforks** [comment]
Running into this too. Heyo.

### Reproduce

#### random public repo
`git clone https://github.com/openshift/cluster-logging-operator`
`cd internal/metrics`
`go-testcov .`

```
[~/Code/public/cluster-logging-operator/internal/metrics (master)] ➔ go-testcov .
ok  	github.com/openshift/cluster-logging-operator/internal/metrics	0.526s	coverage: 81.8% of statements
panic: open internal/metrics/dashboards.go: no such file or directory

goroutine 1 [running]:
main.check(...)
	/Users/jyel/Code/public/go-testcov/utils.go:17
main.readFile({0x14000108446?, 0x0?})
	/Users/jyel/Code/public/go-testcov/utils.go:57 +0x60
main.configuredUntested({0x14000108446?, 0x4c?})
	/Users/jyel/Code/public/go-testcov/main.go:220 +0x24
main.checkCoverage.func1({0x14000108418, 0x4c}, {0x1400010a0e0, 0x2, 0x2})
	/Users/jyel/Code/public/go-testcov/main.go:88 +0xcc
main.iterateSorted(0x140000c7cd0, 0x140000c7cb0)
	/Users/jyel/Code/public/go-testcov/utils.go:71 +0x198
main.checkCoverage({0x1049f4877?, 0x2?})
	/Users/jyel/Code/public/go-testcov/main.go:82 +0xc0
main.goTestCheckCoverage({0x140000ae010, 0x1, 0x104aaf680?})
	/Users/jyel/Code/public/go-testcov/main.go:63 +0x220
main.main()
	/Users/jyel/Code/public/go-testcov/main.go:13 +0x54
```

cc @grosser

**Comment by grosser** [comment]
lol still messing with go I see :D

I think we need to drop `// untested` support in this case ... kinda ugly and leads to more issues, but means it's usable without modifying the repo (send a warn and move on).
Ideally also add a feature that allows specifying the file under test with a magic comment in the test file.

**Comment by grosser** [comment]
If you can make a PR that'd be great, otherwise I can give it a try in a few days 🤞

**Comment by eatwithforks** [comment]
all go and no ruby makes me go crazy.

How do I build this binary locally to test code changes?

**Comment by grosser** [comment]
`go install .` should do it ... or just `go build .` and then `./go-testcov`
