### ISSUE TITLE
Feature request: display line number of untested sections comment

### ISSUE THREAD

**Issue by adammw** [grosser/go-testcov#16]
Currently when the go-testcov tool recommends to decrement the untested sections counter comment, it mentions only the file name:
e.g.
```
pkg/foo/bar.go has less uncovered sections (29 current vs 31 configured), decrement configured uncovered?
```

Ideally it would also include the line number the untested sections comment is on, allowing IDEs to jump directly to the relevant line for update.

**Comment by grosser** [comment]
v1.6.0
